DOMAIN = "p2000"

DEFAULT_NAME = "p2000"
DEFAULT_ICON = "mdi:ambulance"
DEFAULT_SCAN_INTERVAL = 30
MIN_SCAN_INTERVAL = 10
MAX_SCAN_INTERVAL = 3600

CONF_ICON = "icon"
CONF_GEMEENTEN = "gemeenten"
CONF_CAPCODES = "capcodes"
CONF_REGIOS = "regios"
CONF_DISCIPLINES = "disciplines"
CONF_PRIO1 = "prio1"
